import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const ErrorPage: NextPage = () => {
  return (
    <div className="flex flex-col items-center min-h-screen justify-center">
      <Head>
        <title>FastPaper • 500</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        <p className="text-2xl mb-3">There is an error, try again later.</p>
        <Link href="/">
          <a className="self-start text-gray-500 hover:text-gray-700">
            Back to home
          </a>
        </Link>
      </div>
    </div>
  );
};

export default ErrorPage;
